In [1]:
import numpy as np

In [6]:
data = np.array([[0,0],[4,4],[0,4],[4,0]])
x = data[:,0]; print(x)
y = data[:,1]; print(y)
np.cov(x,y, bias=True)

[0 4 0 4]
[0 4 4 0]


array([[4., 0.],
       [0., 4.]])

In [7]:
data = np.array([[1,2], [5,4]])
x = data[:,0]; print(x)
y = data[:,1]; print(y)
np.cov(x,y, bias=True)

[1 5]
[2 4]


array([[4., 2.],
       [2., 1.]])

In [9]:
data = np.array([[1,2], [7,4]])
x = data[:,0]; print(x)
y = data[:,1]; print(y)
np.cov(x,y, bias=True)

[1 7]
[2 4]


array([[9., 3.],
       [3., 1.]])

In [11]:
# add vector [2,2] to each row
data = np.array([[1,2], [7,4]]) + np.array([2,2]); print(data)
x = data[:,0]; print(x)
y = data[:,1]; print(y)
np.cov(x,y, bias=True)

[[3 4]
 [9 6]]
[3 9]
[4 6]


array([[9., 3.],
       [3., 1.]])