In [17]:
import numpy as np
np.mean([1,2,3])

2.0

In [18]:
m1 = np.matrix(range(1,10)).reshape(3,3)
m1.mean(axis=1)

matrix([[2.],
        [5.],
        [8.]])

In [36]:
data = [[1,3,5], [2,4,3], [3,5,1]]
m2 = np.matrix(data)
m2

matrix([[1, 3, 5],
        [2, 4, 3],
        [3, 5, 1]])

In [37]:
(2*m2).mean(axis=1)

matrix([[6.],
        [6.],
        [6.]])

In [27]:
m2[:,0]

matrix([[1],
        [2],
        [3]])

In [38]:
m3 = np.hstack([m2, m2[:,0]])
m3

matrix([[1, 3, 5, 1],
        [2, 4, 3, 2],
        [3, 5, 1, 3]])

In [39]:
m3.mean(axis=1)

matrix([[2.5 ],
        [2.75],
        [3.  ]])

In [40]:
m2.mean(axis=1)+m2[:,0]

matrix([[4.],
        [5.],
        [6.]])

In [0]:
img = 